[Android_Snapdragon_HighEnd DeviceProfile]

DeviceType=Android
BaseProfileName=Android

; =====================================================
; WUTHERING WAVES 3.4
; SNAPDRAGON HIGH END
; =====================================================

; ---------------------
; RESOLUTION
; ---------------------

+CVars=r.ScreenPercentage=100
+CVars=r.MobileContentScaleFactor=2.0

; ---------------------
; SNAPDRAGON SUPER RESOLUTION
; ---------------------

+CVars=r.GSR.Enabled=1

; ---------------------
; KURO FRAME INTERPOLATION
; ---------------------

+CVars=r.KuroFI.Enable=1

; ---------------------
; KURO STREAMING
; ---------------------

+CVars=r.Streaming.UsingNewKuroStreaming=1
+CVars=r.Streaming.UsingKuroStreamingPriority=3

+CVars=r.Streaming.PoolSize=1536
+CVars=r.Streaming.MipBias=0

; ---------------------
; VIEW DISTANCE
; ---------------------

+CVars=r.ViewDistanceScale=2.0
+CVars=r.StaticMeshLODDistanceScale=0.5

; ---------------------
; SHADOWS
; ---------------------

+CVars=r.ShadowQuality=3
+CVars=r.Shadow.MaxResolution=2048

; ---------------------
; FOLIAGE
; ---------------------

+CVars=foliage.DensityScale=2.0
+CVars=grass.CullDistanceScale=2.0

; ---------------------
; REFLECTIONS
; ---------------------

+CVars=r.SSR.Quality=3

; ---------------------
; AMBIENT OCCLUSION
; ---------------------

+CVars=r.AmbientOcclusionLevels=3
+CVars=r.AmbientOcclusionMaxQuality=100

; ---------------------
; EFFECTS
; ---------------------

+CVars=fx.Niagara.QualityLevel=3

; ---------------------
; CLOUDS
; ---------------------

+CVars=r.KuroVolumeCloudEnable=1

; ---------------------
; VRS
; ---------------------

+CVars=r.VRS.EnableMaterial=true
+CVars=r.VRS.EnableMesh=true

; ---------------------
; WORLD PARTITION
; ---------------------

+CVars=wp.Runtime.PlannedLoadingRangeScale=1.2

; ---------------------
; SHADER CACHE
; ---------------------

+CVars=r.PSO.LRUCapacity=16384

; ---------------------
; DEVICE SCORE
; ---------------------

DeviceScore=12000