[Android_Snapdragon_Low DeviceProfile]

DeviceType=Android
BaseProfileName=Android

; =====================================================
; WUTHERING WAVES 3.4
; SNAPDRAGON LOW END
; =====================================================

; ---------------------
; RESOLUTION
; ---------------------

+CVars=r.ScreenPercentage=70

; ---------------------
; SNAPDRAGON SUPER RESOLUTION
; ---------------------

+CVars=r.GSR.Enabled=1

; ---------------------
; KURO STREAMING
; ---------------------

+CVars=r.Streaming.UsingNewKuroStreaming=1
+CVars=r.Streaming.UsingKuroStreamingPriority=3

+CVars=r.Streaming.PoolSize=384
+CVars=r.Streaming.MipBias=8

; ---------------------
; VIEW DISTANCE
; ---------------------

+CVars=r.ViewDistanceScale=0.7
+CVars=r.StaticMeshLODDistanceScale=1.2

; ---------------------
; SHADOWS
; ---------------------

+CVars=r.ShadowQuality=0
+CVars=r.Shadow.MaxResolution=256

; ---------------------
; FOLIAGE
; ---------------------

+CVars=foliage.DensityScale=0.3

; ---------------------
; EFFECTS
; ---------------------

+CVars=fx.Niagara.QualityLevel=0

; ---------------------
; KURO FRAME INTERPOLATION
; ---------------------

+CVars=r.KuroFI.Enable=1

; ---------------------
; WORLD PARTITION
; ---------------------

+CVars=wp.Runtime.PlannedLoadingRangeScale=0.4

; ---------------------
; DEVICE SCORE
; ---------------------

DeviceScore=3500