[Android_HighEnd DeviceProfile]

DeviceType=Android
BaseProfileName=Android

; =====================================================
; WUTHERING WAVES 3.4
; HIGH END
; =====================================================

; ---------------------
; RESOLUTION
; ---------------------

+CVars=r.ScreenPercentage=100
+CVars=r.MobileContentScaleFactor=1.5

; ---------------------
; KURO STREAMING
; ---------------------

+CVars=r.Streaming.UsingNewKuroStreaming=1
+CVars=r.Streaming.UsingKuroStreamingPriority=3

+CVars=r.Streaming.PoolSize=1024
+CVars=r.Streaming.MipBias=0

; ---------------------
; VIEW DISTANCE
; ---------------------

+CVars=r.ViewDistanceScale=1.5
+CVars=r.StaticMeshLODDistanceScale=0.5

; ---------------------
; SHADOWS
; ---------------------

+CVars=r.ShadowQuality=3
+CVars=r.Shadow.DistanceScale=1.5
+CVars=r.Shadow.MaxResolution=1024

; ---------------------
; FOLIAGE
; ---------------------

+CVars=foliage.DensityScale=1.5
+CVars=grass.CullDistanceScale=1.5

; ---------------------
; REFLECTIONS
; ---------------------

+CVars=r.SSR.Quality=2

; ---------------------
; AMBIENT OCCLUSION
; ---------------------

+CVars=r.AmbientOcclusionLevels=2
+CVars=r.AmbientOcclusionMaxQuality=60

; ---------------------
; EFFECTS
; ---------------------

+CVars=fx.Niagara.QualityLevel=3

; ---------------------
; CLOUDS
; ---------------------

+CVars=r.KuroVolumeCloudEnable=1

; ---------------------
; KURO FRAME INTERPOLATION
; ---------------------

+CVars=r.KuroFI.Enable=1

; ---------------------
; WORLD PARTITION
; ---------------------

+CVars=wp.Runtime.PlannedLoadingRangeScale=1.0

; ---------------------
; SHADER CACHE
; ---------------------

+CVars=r.PSO.LRUCapacity=8192

; ---------------------
; DEVICE SCORE
; ---------------------

DeviceScore=10000