[Android_VeryHigh DeviceProfile]
; --- 3.3 CORE ENGINE OVERRIDES ---
CVars=m.LowMemoryDeviceThreshold=5800
CVars=r.Streaming.UsingNewKuroStreaming=1
CVars=r.KuroFI.Enable=1
CVars=r.FEstimation.Option=1

; --- RESOLUTION & BALANCED PERFORMANCE ---
CVars=r.MobileContentScaleFactor=1.0
CVars=r.SecondaryScreenPercentage.GameViewport=100
CVars=r.ScreenPercentage=85
CVars=!r.ScreenPercentage=85

; --- 3.3 ANNIVERSARY MAP BALANCED OPTIMIZATION ---
CVars=r.LandscapeLOD0ScreenSizeScale=1.5
CVars=r.Kuro.Foliage.NearCullDistanceMin=6000
CVars=r.Kuro.Foliage.NearCullDistanceMax=6500
CVars=r.imp.SSMbScaleLod0=0.0
CVars=r.imp.SSMbScaleLod1=0.0
CVars=r.Mobile.DeviceEvaluation=3

[Android_Default DeviceProfile]
BaseProfileName=Android_VeryHigh
DeviceScore=3000

[Nubia_Z17S DeviceProfile]
BaseProfileName=Android_VeryHigh
DeviceScore=3000

[Honor_BMH_AN10 DeviceProfile]
BaseProfileName=Android_VeryHigh
DeviceScore=3000

[Vivo_V2231A DeviceProfile]
BaseProfileName=Android_VeryHigh
DeviceScore=3000

[Xiaomi_O1 DeviceProfile]
DeviceScore=3000

[Android_Adreno7xx DeviceProfile]
BaseProfileName=Android_VeryHigh
DeviceScore=3000

[Android_Adreno740 DeviceProfile]
BaseProfileName=Android_VeryHigh
DeviceScore=3000

[Android_Adreno750 DeviceProfile]
BaseProfileName=Android_VeryHigh
DeviceScore=3000

[Android_Adreno8xx DeviceProfile]
BaseProfileName=Android_VeryHigh
DeviceScore=3000

[Android_Adreno810 DeviceProfile]
BaseProfileName=Android_VeryHigh
DeviceScore=3000

[Android_Adreno830 DeviceProfile]
BaseProfileName=Android_VeryHigh
DeviceScore=3000