[Android_VeryHigh DeviceProfile]
; --- 3.3 CORE ENGINE OVERRIDES ---
CVars=m.LowMemoryDeviceThreshold=5800
CVars=r.Streaming.UsingNewKuroStreaming=1
CVars=r.KuroFI.Enable=1
CVars=r.FEstimation.Option=1

; --- RESOLUTION & SCALING (Priority Force) ---
CVars=r.MobileContentScaleFactor=1.0
CVars=r.ScreenPercentage=70
CVars=!r.ScreenPercentage=70

; --- ANNIVERSARY MAP GEOMETRY REDUCTION ---
CVars=r.LandscapeLOD0ScreenSizeScale=0.5
CVars=r.Kuro.Foliage.NearCullDistanceMin=2000
CVars=r.Kuro.Foliage.NearCullDistanceMax=2500
CVars=r.imp.SSMbScaleLod0=0.0
CVars=r.imp.SSMbScaleLod1=0.0
CVars=r.Mobile.DeviceEvaluation=3

[Android_Default DeviceProfile]
BaseProfileName=Android_VeryHigh
DeviceScore=3000

; ---- ARM MALI ----
[Android_Mali_T6xx DeviceProfile]
BaseProfileName=Android_VeryHigh
DeviceScore=3000

[Android_Mali_T8xx DeviceProfile]
BaseProfileName=Android_VeryHigh
DeviceScore=3000

[Android_Mali_G5x_Low DeviceProfile]
BaseProfileName=Android_VeryHigh
DeviceScore=3000

[Android_Mali_G71 DeviceProfile]
BaseProfileName=Android_VeryHigh
DeviceScore=3000

[Android_Mali_G72 DeviceProfile]
BaseProfileName=Android_VeryHigh
DeviceScore=3000

[Android_Mali_G76 DeviceProfile]
BaseProfileName=Android_VeryHigh
DeviceScore=3000

[Android_Mali_G710 DeviceProfile]
BaseProfileName=Android_VeryHigh
DeviceScore=3000

; ---- SAMSUNG XCLIPSE ----
[Android_Xclipse5xx DeviceProfile]
BaseProfileName=Android_VeryHigh
DeviceScore=3000

[Android_Xclipse9xx DeviceProfile]
BaseProfileName=Android_VeryHigh
DeviceScore=3000

; ---- POWERVR ----
[Android_PowerVR_GE8xxx DeviceProfile]
BaseProfileName=Android_VeryHigh
DeviceScore=3000

[Android_PowerVR_GM9xxx DeviceProfile]
BaseProfileName=Android_VeryHigh
DeviceScore=3000