[Android_Snapdragon_BalanceVisual DeviceProfile]

DeviceType=Android
BaseProfileName=Android

; =====================================================
; WUTHERING WAVES 3.4
; SNAPDRAGON BALANCED VISUAL
; =====================================================

; ---------------------
; RESOLUTION
; ---------------------

+CVars=r.ScreenPercentage=100
+CVars=r.MobileContentScaleFactor=1.5

; ---------------------
; SNAPDRAGON SUPER RESOLUTION
; ---------------------

+CVars=r.GSR.Enabled=1

; ---------------------
; KURO FRAME INTERPOLATION
; ---------------------

+CVars=r.KuroFI.Enable=1

; ---------------------
; KURO STREAMING
; ---------------------

+CVars=r.Streaming.UsingNewKuroStreaming=1
+CVars=r.Streaming.UsingKuroStreamingPriority=3

+CVars=r.Streaming.PoolSize=1024
+CVars=r.Streaming.MipBias=1

; ---------------------
; VIEW DISTANCE
; ---------------------

+CVars=r.ViewDistanceScale=1.2
+CVars=r.StaticMeshLODDistanceScale=0.7

; ---------------------
; SHADOWS
; ---------------------

+CVars=r.ShadowQuality=2
+CVars=r.Shadow.MaxResolution=1024

; ---------------------
; FOLIAGE
; ---------------------

+CVars=foliage.DensityScale=1.2
+CVars=grass.CullDistanceScale=1.2

; ---------------------
; REFLECTIONS
; ---------------------

+CVars=r.SSR.Quality=2

; ---------------------
; AMBIENT OCCLUSION
; ---------------------

+CVars=r.AmbientOcclusionLevels=2
+CVars=r.AmbientOcclusionMaxQuality=50

; ---------------------
; EFFECTS
; ---------------------

+CVars=fx.Niagara.QualityLevel=2

; ---------------------
; CLOUDS
; ---------------------

+CVars=r.KuroVolumeCloudEnable=1

; ---------------------
; VRS
; ---------------------

+CVars=r.VRS.EnableMaterial=true
+CVars=r.VRS.EnableMesh=true

; ---------------------
; WORLD PARTITION
; ---------------------

+CVars=wp.Runtime.PlannedLoadingRangeScale=0.8

; ---------------------
; SHADER CACHE
; ---------------------

+CVars=r.PSO.LRUCapacity=8192

; ---------------------
; DEVICE SCORE
; ---------------------

DeviceScore=9000