[Android_BalanceVisual DeviceProfile]

DeviceType=Android
BaseProfileName=Android

; =====================================================
; WUTHERING WAVES 3.4
; BALANCED VISUAL
; =====================================================

; ---------------------
; RESOLUTION
; ---------------------

+CVars=r.ScreenPercentage=100
+CVars=r.MobileContentScaleFactor=1.0

; ---------------------
; KURO STREAMING
; ---------------------

+CVars=r.Streaming.UsingNewKuroStreaming=1
+CVars=r.Streaming.UsingKuroStreamingPriority=3

+CVars=r.Streaming.PoolSize=768
+CVars=r.Streaming.MipBias=2

; ---------------------
; VIEW DISTANCE
; ---------------------

+CVars=r.ViewDistanceScale=1.0
+CVars=r.StaticMeshLODDistanceScale=0.8

; ---------------------
; SHADOWS
; ---------------------

+CVars=r.ShadowQuality=2
+CVars=r.Shadow.DistanceScale=1.0
+CVars=r.Shadow.MaxResolution=512

; ---------------------
; FOLIAGE
; ---------------------

+CVars=foliage.DensityScale=1.0
+CVars=grass.CullDistanceScale=1.0

; ---------------------
; EFFECTS
; ---------------------

+CVars=fx.Niagara.QualityLevel=2

; ---------------------
; CLOUDS
; ---------------------

+CVars=r.KuroVolumeCloudEnable=1

; ---------------------
; KURO FRAME INTERPOLATION
; ---------------------

+CVars=r.KuroFI.Enable=1

; ---------------------
; WORLD PARTITION
; ---------------------

+CVars=wp.Runtime.PlannedLoadingRangeScale=0.8

; ---------------------
; SHADER CACHE
; ---------------------

+CVars=r.PSO.LRUCapacity=4096

; ---------------------
; DEVICE SCORE
; ---------------------

DeviceScore=7000